<?php

return [
    'appName' => 'Si Kosman', 
    'adminEmail' => 'admin@example.com',
    'senderEmail' => 'noreply@example.com',
    'senderName' => 'Example.com mailer',
    'bsVersion' => '4.x',
    'maskMoneyOptions' => [
        'prefix' => 'Rp ',
        'suffix' => '',
        'affixesStay' => true,
        'thousands' => '.',
        'decimal' => ',',
        'precision' => 0,
        'allowZero' => false,
        'allowNegative' => false,
    ],
    'bsDependencyEnabled' => false,
    'gridConfigv2' => [
        'headerContainer' => ['style' => 'top:50px', 'class' => 'kv-table-header'], // offset from top
        'floatHeader' => true, // table header floats when you scroll
        'floatPageSummary' => true, // table page summary floats when you scroll
        'floatFooter' => false, // disable floating of table footer
        'pjax' => false, // pjax is set to always false for this demo
        // parameters from the demo form
        'responsive' => false,
        'bordered' => true,
        'striped' => false,
        'condensed' => true,
        'hover' => true,
        'showPageSummary' => true,
        'panel' => [
            //'after' => '<div class="float-right float-end"><button type="button" class="btn btn-primary" onclick="var keys = $("#kv-grid-demo").yiiGridView("getSelectedRows").length; alert(keys > 0 ? "Downloaded " + keys + " selected books to your account." : "No rows selected for download.");"><i class="fas fa-download"></i> Download Selected</button></div><div style="padding-top: 5px;"><em>* The page summary displays SUM for first 3 amount columns and AVG for the last.</em></div><div class="clearfix"></div>',
            'heading' => '<i class="fas fa-book"></i>  List',
            'type' => 'dark',
        // 'before' => '<div style="padding-top: 7px;"><em>* Resize table columns just like a spreadsheet by dragging the column edges.</em></div>',
        ],
        // set export properties
        'export' => [
            'fontAwesome' => true
        ],
        'toggleDataContainer' => ['class' => 'btn-group mr-2 me-2'],
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 10],
        'itemLabelSingle' => 'data',
        'itemLabelPlural' => 'datas'
    ], 
    'gridConfig' => [
        'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => '-'],
        'autoXlFormat' => true,
        'export' => [
            'showConfirmAlert' => false,
            'target' => kartik\grid\GridView::TARGET_BLANK
        ],
        'exportConfig' => [
            kartik\grid\GridView::PDF => [
                'label' => Yii::t('kvgrid', 'PDF'),
                'iconOptions' => ['class' => 'text-danger'],
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => Yii::t('kvgrid', 'cbm-transmisi-export-' . date('d-m-Y')),
                'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
                'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
                'mime' => 'application/pdf',
                'config' => [
                    'mode' => 'c',
                    'methods' => [
                        'SetHeader' => [
                            ['odd' => [
                                    'L' => [
                                        'content' => '',
                                    ],
                                    'C' => [
                                        'content' => 'CBM Transmisi Export',
                                        'font-size' => 12,
                                        'font-style' => 'B',
                                        'font-family' => 'arial',
                                        'color' => '#333333',
                                    ],
                                    'R' => [
                                        'content' => 'Generated : ' . date('d-m-Y H:i:s'),
                                    ],
                                    'line' => true,
                                ]
                            ]
                        ],
                        'SetFooter' => [
                            ['odd' => 'cbm-transmisi-export', 'even' => 'cbm-transmisi-export']
                        ],
                    ],
                    'options' => [
                        'title' => 'cbm-transmisi-export',
                        'subject' => Yii::t('kvgrid', 'PDF export generated by grid extension'),
                        'keywords' => Yii::t('kvgrid', 'krajee, grid, export, grid, pdf')
                    ],
                    //'contentBefore' => 'cbm-transmisi-export-' . date('d-m-Y'), 
                    'contentAfter' => ''
                ]
            ],
            kartik\grid\GridView::EXCEL => ['filename' => Yii::t('kvgrid', 'cbm-transmisi-export-' . date('d-m-Y')),],
            kartik\grid\GridView::CSV => ['filename' => Yii::t('kvgrid', 'cbm-transmisi-export-' . date('d-m-Y')),]
        ],
        'pjax' => true,
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'responsiveWrap' => false,
        'hover' => true,
        'pager' => [
            'options' => ['class' => 'pagination'], // set clas name used in ui list of pagination
            'prevPageLabel' => '<', // Set the label for the "previous" page button
            'nextPageLabel' => '>', // Set the label for the "next" page button
            'firstPageLabel' => '<<', // Set the label for the "first" page button
            'lastPageLabel' => '>>', // Set the label for the "last" page button
            'nextPageCssClass' => 'next', // Set CSS class for the "next" page button
            'prevPageCssClass' => 'prev', // Set CSS class for the "previous" page button
            'firstPageCssClass' => 'first', // Set CSS class for the "first" page button
            'lastPageCssClass' => 'last', // Set CSS class for the "last" page button
        ],
        'floatHeader' => false,
        "resizableColumns" => false,
        'persistResize' => false,
        'resizeStorageKey' => 'srintamiV4-' . date("m"),
        'panel' => [
            'heading' => false,
            'footer' => false,
            'type' => kartik\grid\GridView::TYPE_DEFAULT
        ],
         'panelBeforeTemplate' => '{toolbarContainer} <div class="pull-left">{summary}</div> <div class="clearfix"></div>',
        'panelTemplate' => '
        <div class="panel panel-{type}">
            {panelBefore}
            {items}
            <div class="panel-pager">
            <br>
            {pager}
                <div class="clearfix"></div>
            </div>
        </div>'
    ]
];
